INSERT INTO State(StateID, StateAbbrv, StateName)
    VALUES(nextval('state_seq'), 'AL', 'Alabama'),
          (nextval('state_seq'), 'AK', 'Alaska'),
          (nextval('state_seq'), 'AZ', 'Arizona'),
          (nextval('state_seq'), 'AR', 'Arkansas'),
          (nextval('state_seq'), 'CA', 'California'),
          (nextval('state_seq'), 'CO', 'Colorado'),
          (nextval('state_seq'), 'CT', 'Connecticut'),
          (nextval('state_seq'), 'DE', 'Delaware'),
          (nextval('state_seq'), 'FL', 'Florida'),
          (nextval('state_seq'), 'GA', 'Georgia'),
          (nextval('state_seq'), 'HI', 'Hawaii'),
          (nextval('state_seq'), 'ID', 'Idaho'),
          (nextval('state_seq'), 'IL', 'Illinois'),
          (nextval('state_seq'), 'IN', 'Indiana'),
          (nextval('state_seq'), 'IA', 'Iowa'),
          (nextval('state_seq'), 'KS', 'Kansas'),
          (nextval('state_seq'), 'KY', 'Kentucky'),
          (nextval('state_seq'), 'LA', 'Louisiana'),
          (nextval('state_seq'), 'ME', 'Maine'),
          (nextval('state_seq'), 'MD', 'Maryland'),
          (nextval('state_seq'), 'MA', 'Massachusetts'),
          (nextval('state_seq'), 'MI', 'Michigan'),
          (nextval('state_seq'), 'MN', 'Minnesota'),
          (nextval('state_seq'), 'MS', 'Mississippi'),
          (nextval('state_seq'), 'MO', 'Missouri'),
          (nextval('state_seq'), 'MT', 'Montana'),
          (nextval('state_seq'), 'NE', 'Nebraska'),
          (nextval('state_seq'), 'NV', 'Nevada'),
          (nextval('state_seq'), 'NH', 'New Hampshire'),
          (nextval('state_seq'), 'NJ', 'New Jersey'),
          (nextval('state_seq'), 'NM', 'New Mexico'),
          (nextval('state_seq'), 'NY', 'New York'),
          (nextval('state_seq'), 'NC', 'North Carolina'),
          (nextval('state_seq'), 'ND', 'North Dakota'),
          (nextval('state_seq'), 'OH', 'Ohio'),
          (nextval('state_seq'), 'OK', 'Oklahoma'),
          (nextval('state_seq'), 'OR', 'Oregon'),
          (nextval('state_seq'), 'PA', 'Pennsylvania'),
          (nextval('state_seq'), 'RI', 'Rhode Island'),
          (nextval('state_seq'), 'SC', 'South Carolina'),
          (nextval('state_seq'), 'SD', 'South Dakota'),
          (nextval('state_seq'), 'TN', 'Tennessee'),
          (nextval('state_seq'), 'TX', 'Texas'),
          (nextval('state_seq'), 'UT', 'Utah'),
          (nextval('state_seq'), 'VT', 'Vermont'),
          (nextval('state_seq'), 'VA', 'Virginia'),
          (nextval('state_seq'), 'WA', 'Washington'),
          (nextval('state_seq'), 'WV', 'West Virginia'),
          (nextval('state_seq'), 'WI', 'Wisconsin'),
          (nextval('state_seq'), 'WY', 'Wyoming');

INSERT INTO ShipSpeed(ShipSpeedID, ShipSpeedName, ShipSpeedPrice, ShipSpeedDesc)
    VALUES(nextval('shipspeed_seq'), 'Overnight', 25.0, 'Fastest possible delivery'),
	      (nextval('shipspeed_seq'), '2-Day', 10.0, 'When you are in a hurry'),
		  (nextval('shipspeed_seq'), 'Standard', 5.0, 'Standard USPS Delivery (Roughly 5 days)');
